apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-deploy
spec:
  description: "Deploy the image to the cluster"
  workspaces:
    - name: source
      description: "The source code will be cloned into this workspace"
      mountPath: /workspace/source
  params:
    - name: MANIFEST
      description: "Directory of the manifest file for deployment"
      default: "deploy"
    - name: DEPLOY
      description: "File name for deployment"
      default: "deploy.yaml"
  steps:
    - name: check-source
      image: ubuntu:latest
      workingDir: /workspace/source
      script: |
        #!/usr/bin/env bash
        pwd
        ls -la
        cd $(workspaces.source.path)/$(params.MANIFEST)/
        ls -la
    - name: deploy
      image: quay.io/openshift/origin-cli
      script: |
        #!/usr/bin/env bash
        oc whoami
        echo ===========================
        oc get project
        echo ===========================
        oc apply -f $(workspaces.source.path)/$(params.MANIFEST)/$(params.DEPLOY)
    - name: check-deploy
      image: quay.io/openshift/origin-cli
      script: |
        #!/usr/bin/env bash
        oc get pod
        echo ===========================
        oc get service
        echo ===========================
        oc get route