apiVersion: apps/v1
kind: Deployment
metadata:
  name: okd-tekton-workshop
spec:
  selector:
    matchLabels:
      app: okd-tekton-workshop
  template:
    metadata:
      labels:
        app: okd-tekton-workshop
    spec:
      containers:
      - name: okd-tekton-workshop
        image: pewpewtron/okd-tekton-workshop:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: okd-tekton-workshop-service
spec:
  selector:
    app: okd-tekton-workshop
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: okd-tekton-workshop-route
spec:
  port:
    targetPort: 3000
  to:
    kind: Service
    name: okd-tekton-workshop-service
